---
- hosts: "{{ passed_in_hosts }}"
  #become: yes
  remote_user: "{{ passed_in_remote_user }}"
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: "{{ passed_in_private_key }}"

  tasks:
    - name: install jq, JSON parser
      yum:
        name: jq
        state: present
      become: yes
      
    - name: install Docker
      yum:
        name: docker
        state: present
      become: yes

    - name: Start and Enable Docker
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Download Docker Compose binary
      shell: "curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
      args:
        creates: /usr/local/bin/docker-compose
      become: yes
    
    - name: Make Docker Compose executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '+x'
      become: yes
    
    - name: Change ownership of /var/run/docker.sock
      become: yes
      become_user: root
      command: chown -R {{ ansible_env.USER }}:{{ ansible_env.USER }} /var/run/docker.sock